name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 16.16.255.61                  # Your EC2 public IP
        username: ubuntu                    # Default EC2 username for Ubuntu AMIs
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key from GitHub Secrets
        script: |
          set -x # Print each command before execution for debugging
          ssh -v ubuntu@16.16.255.61 << 'EOF'  # Start SSH session with verbose output
            # Navigate to your project directory
            cd ~/flask-cicd-demo
            
            # Pull latest changes from GitHub
            git pull origin main
            
            # Stop and remove existing containers
            docker-compose down
            
            # Build and restart containers
            docker-compose up -d --build
          EOF

