name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t kavya9864/flask-ci-cd-demo .

    - name: Push Docker image to Docker Hub
      run: docker push kavya9864/flask-ci-cd-demo

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull kavya9864/flask-ci-cd-demo
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 5000:5000 --name flask-app kavya9864/flask-ci-cd-demo
